FROM jetbrains/teamcity-agent:2021.2-linux-sudo
RUN sudo apt-get update
RUN sudo apt-get install bsdmainutils -yq
RUN sudo apt-get install tree -yq
RUN sudo apt-get install openjdk-8-jdk -yq
RUN sudo apt-get install openjdk-17-jdk -yq
RUN sudo apt-get install binutils -yq
RUN sudo apt-get install lsof -yq
RUN sudo apt-get install curl -yq
  
