git clone https://github.com/OpenHFT/Java-Thread-Affinity.git
git clone https://github.com/OpenHFT/Java-Lang.git
git clone https://github.com/OpenHFT/Chronicle-Queue.git
git clone https://github.com/OpenHFT/Chronicle-Map.git
git clone https://github.com/OpenHFT/Chronicle-Egine.git
git clone https://github.com/OpenHFT/Java-Runtime-Compiler.git
git clone https://github.com/OpenHFT/TransFIX.git
git clone https://github.com/OpenHFT/SAXophone.git
git clone git@github.com:OpenHFT/Chronicle-Logger.git
