#!/bin/sh
git clone git@github.com:OpenHFT/RFC.git
git clone git@github.com:OpenHFT/Java-Thread-Affinity.git
git clone git@github.com:OpenHFT/Java-Runtime-Compiler.git
git clone git@github.com:OpenHFT/Chronicle-Core.git
git clone git@github.com:OpenHFT/Chronicle-Algorithms.git
git clone git@github.com:OpenHFT/Chronicle-Bytes.git
git clone git@github.com:OpenHFT/Chronicle-Values.git
git clone git@github.com:OpenHFT/Chronicle-Threads.git
git clone git@github.com:OpenHFT/Chronicle-Wire.git
git clone git@github.com:OpenHFT/Chronicle-Network.git
git clone git@github.com:OpenHFT/Chronicle-Websocket-Jetty.git
git clone git@github.com:OpenHFT/Chronicle-Queue.git
git clone git@github.com:OpenHFT/Chronicle-Map.git
git clone git@github.com:OpenHFT/Chronicle-Logger.git
git clone git@github.com:OpenHFT/Chronicle-Engine.git
git clone git@github.com:OpenHFT/Chronicle-Salt.git
git clone git@github.com:OpenHFT/Chronicle-Decentred.git
git clone git@github.com:OpenHFT/Chronicle-Coder.git
