<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2013-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0

-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.openhft</groupId>
        <artifactId>root-parent-pom</artifactId>
        <version>1.27ea5-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <artifactId>java-parent-pom</artifactId>
    <version>1.27ea2-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>OpenHFT/Java Parent POM</name>
    <description>This parent pom is used by all the OpenHft java projects</description>

    <organization>
        <name>Chronicle Software Ltd</name>
        <url>https://chronicle.software/</url>
    </organization>

    <properties>
        <sonar.organization>openhft</sonar.organization>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
        <!-- Define the target coverage thresholds as properties -->
        <jacoco.line.coverage>0.8</jacoco.line.coverage>
        <jacoco.branch.coverage>0.7</jacoco.branch.coverage>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <license.header>Copyright 2013-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0</license.header>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>4.6</version>

                <configuration>
                    <!-- One-line header; no newlines -->
                    <inlineHeader>${license.header}</inlineHeader>
                    <failIfUnknown>false</failIfUnknown>
                    <excludes>
                        <exclude>LICENSE</exclude>
                        <exclude>**/*.adoc</exclude>
                        <exclude>**/*.md</exclude>
                        <exclude>**/*.txt</exclude>
                        <exclude>docs/antora/**</exclude>
                        <exclude>src/main/config/**</exclude>
                        <exclude>src/main/docs/**</exclude>
                        <exclude>src/main/resources/**</exclude>
                        <exclude>src/test/resources/**</exclude>
                        <exclude>target/**</exclude>
                        <exclude>**/*.versionsBackup</exclude>
                        <exclude>surefire-buildagent/**</exclude>
                    </excludes>

                    <mapping>
                        <!-- Languages with // comments -->
                        <java>DOUBLESLASH_STYLE</java>
                        <kt>DOUBLESLASH_STYLE</kt>
                        <scala>DOUBLESLASH_STYLE</scala>
                        <groovy>DOUBLESLASH_STYLE</groovy>
                        <js>DOUBLESLASH_STYLE</js>
                        <ts>DOUBLESLASH_STYLE</ts>

                        <!-- Properties, YAML, shells, Python: # comments -->
                        <properties>SCRIPT_STYLE</properties>
                        <yml>SCRIPT_STYLE</yml>
                        <yaml>SCRIPT_STYLE</yaml>
                        <sh>SCRIPT_STYLE</sh>
                        <py>SCRIPT_STYLE</py>
                    </mapping>
                </configuration>

                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <project.build.directory>${project.build.directory}</project.build.directory>
                    </systemPropertyVariables>
                    <enableAssertions>true</enableAssertions>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-scm-publish-plugin</artifactId>
                <configuration>
                    <checkoutDirectory>${project.build.directory}/scmpublish/javadoc</checkoutDirectory>
                    <checkinComment>Publishing javadoc for ${project.artifactId}:${project.version}</checkinComment>
                    <content>${project.reporting.outputDirectory}</content>
                    <skipDeletedFiles>true</skipDeletedFiles>
                    <pubScmUrl>scm:git:git@github.com:OpenHFT/${project.artifactId}
                    </pubScmUrl>
                    <scmBranch>gh-pages</scmBranch>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>-Xlint:all,-options,-processing</arg>
                        <arg>-parameters</arg>
                    </compilerArgs>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                    <failOnWarning>true</failOnWarning>
                    <showDeprecation>true</showDeprecation>
                    <showWarnings>true</showWarnings>
                    <proc>none</proc>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <source>8</source>
                    <additionalOptions>${javadoc.opts}</additionalOptions>
                    <failOnError>true</failOnError>
                    <failOnWarnings>true</failOnWarnings>
                    <excludePackageNames>*.internal:*.internal.*;*.impl;*.impl.*</excludePackageNames>
                    <doclint>all,-missing</doclint>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>doclint-java8-disable</id>
            <activation>
                <jdk>[1.8,)</jdk>
            </activation>
            <properties>
                <javadoc.opts>-Xdoclint:none</javadoc.opts>
            </properties>
        </profile>
    </profiles>

    <scm>
        <connection>scm:git:git@github.com:OpenHFT/OpenHFT.git</connection>
        <developerConnection>scm:git:git@github.com:OpenHFT/OpenHFT.git</developerConnection>
        <url>scm:git:git@github.com:OpenHFT/OpenHFT.git</url>
        <tag>ea</tag>
    </scm>
</project>
