= Java Version Support
Peter Lawrey

Almost all libraries are built in Java 8 and are subsequently tested under Java 8, Java 11 and Java 17 as a part of our continuous integration process. However, some libraries may also be build with more recent Java version as described hereunder:

== Compiles on Java 8, Runs on Java 11 and 17.

These libraries compile on Java 8 and pass all the tests under Java 8, Java 11 and Java 17.

- Chronicle-Core

== Compiles and Runs on Java 8, 11, and 17.

These libraries compile on either Java 8, 11 and 17 and pass all the tests under the version built and higher.

- Chronicle-Algorithms
- Chronicle-Datagrid
- Chronicle-Datagrid-Demo
- Chronicle-FIX
- Chronicle-Map
- Chronicle-Map-Enterprise
- Chronicle-Market-Data-Distributor
- Chronicle-Network 
- Chronicle-Network-Enterprise
- Chronicle-Queue
- Chronicle-Queue-Enterprise
- Chronicle-Ring
- Chronicle-Salt
- Chronicle-Services
- Chronicle-Threads
- Chronicle-Values
- Chronicle-Websocket-Jetty
- Chronicle-Wire-Enterprise
- JLBH

== Running under Java 17 (class path)
When starting a JVM explicitly using the `java` command, the follow command line parameters need to be passed in:

[source, shell script]
----
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED
--add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
----

TIP: Even though not strictly required, we recommend providing the same command line options for Java 11 as for Java 17 as this will remove some warnings in the output logs.