= Version Support
Peter Lawrey

Chronicle Software supports each version for two years from the start of the next minor version. 

All our software has a MAJOR.STAGE.MINOR version. 

The MAJOR version is the generation of the software, where major versions are not compatible with each other.

The STAGE version is the same for all our products e.g 2.20.x or 3.20.x so you know that all the software is part of the same stage.

The MINOR version is the incremental release of the software for a given MAJOR.STAGE.

Once a MAJOR.STAGE is updated to the new version, the previous MAJOR.STAGE-1 starts two years until end of support.

== Commercial Support Agreement

A commercial support agreement is available from mailto:sales@chronicle.software[sales@chronicle.software], free open source support is also available but on a best effort basis. Free support issues are not treated as a high priority unless the issues also affect organisations with a commercial agreement. The support agreement doesn’t just benefit your organisation, but it helps the wider community as it allows us to fund the continued development of our OpenSource libraries.

== Stage release dates and end of support.

|====
| Stage | first released | stable release | end of support | Java versions
| x.23  | 2022 (a) | 2023 (a) | 2025 (a) | 8 & 11 & 17
| x.22  | 2021/08 (a) | 2022 (a) | 2024 (a) | 8 & 11 & 17
| x.21  | 2021/01 | 2021/08 | 2023/08 | 8 & 11
| x.20  | 2020/07 | 2020/12 | 2022/12 | 8 & 11
| x.19  | 2020/02 | 2020/06 | 2022/06 | 8 & 11
| x.17  | 2018/08 | 2019/11 | 2021/11 | 8 & 11
| x.16  | 2018/05 | 2018/08 | 2020/08 | 8
| x.15  | 2017/12 | 2018/05 | 2020/05 | 8
| x.14  | 2017/03 | 2017/12 | 2019/12 | 8
| x.13  | 2016/07 | 2017/03 | 2019/03 | 8
| x.12  | 2016/03 | 2016/07 | 2019/03 | 8
|====
(a) Provisional dates

Java 17 is supported with the x.22 release. x.24 is planned to be the first release that fully takes advantage of Java 17 source features.

NOTE: There was no x.18 release.

== Java 8 support.

We currently support Java 8, 11 and 17.

Once the master branch updates to a new stage, older stages are only updated and released based on client requirement ensuring they stay stable.

Java 11 and Java 17 are supported on the master branch and Java 8 will likely only be supported up to and including the x.22 branch.

== BOM files

We use maven dependency management to express the version set of all our libraries, hence. We always publish a set of artifacts that work together using a BOM file (see details on BOM files link:https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms/[here]).

== EA (Early Access)

We have introduced the characters “ea” into our build versions, to denote our Early Access release. As the name suggests, we release our early access version regularly. Then about every three months we will cut a non "ea" release.

Note: Many organizations use the “ea” release in production, as this contains the latest functionality and fixes.

== Binary Compatibility

Each release is now automatically checked to be binary backward compatible to the first patch release of any version, this also includes the early access release versions.

