MMAnnotationDisabledMessageContextless=-1
MMAnnotationDisabledMessageDuplicate=31
MMAnnotationDisabledMessageGeneric=-1
MMAnnotationDisabledMessageIndexOnly=-1
MMAnnotationDisabledMessageLongWord=-1
MMAnnotationDisabledMessageMissing=47
MMAnnotationDisabledMessageRedundantLineNumber=-1
MMAnnotationDisabledMessageRestatesAssertion=-1
MMAnnotationDisabledMessageRestatesDerivedAssertion=1
MMAnnotationDisabledMessageTooFewMeaningfulWords=26
MMAnnotationDisabledMessageTooLong=-1
MMAnnotationDisabledMessageTooShort=39
MMAnnotationDisabledMessageWhitespaceRun=-1
MMAnnotationDisplayNameMessageContextless=2
MMAnnotationDisplayNameMessageDuplicate=22
MMAnnotationDisplayNameMessageGeneric=7
MMAnnotationDisplayNameMessageIndexOnly=-1
MMAnnotationDisplayNameMessageLongWord=-1
MMAnnotationDisplayNameMessageRedundantLineNumber=-1
MMAnnotationDisplayNameMessageRestatesAssertion=-1
MMAnnotationDisplayNameMessageRestatesDerivedAssertion=3
MMAnnotationDisplayNameMessageTooFewMeaningfulWords=30
MMAnnotationDisplayNameMessageTooLong=-1
MMAnnotationDisplayNameMessageTooShort=41
MMAnnotationDisplayNameMessageWhitespaceRun=-1
MMAnnotationDisplayNameMissing=79
MMAnnotationJUnit4Annotation=68
MMAnnotationJUnit4Assertion=64
MMAnnotationTestOrder=58
MMAssertionAssertAllHeadingLowSignal=-1
MMAssertionAssertJOverrideMessage=4
MMAssertionMessageContextless=34
MMAssertionMessageDuplicate=70
MMAssertionMessageDuplicatesInput=51
MMAssertionMessageGeneric=42
MMAssertionMessageIndexOnly=43
MMAssertionMessageLongWord=27
MMAssertionMessageMissing=75
MMAssertionMessageMissingComparisonValues=40
MMAssertionMessageMissingLoopIndex=61
MMAssertionMessageMissingStringSearchValue=33
MMAssertionMessageMissingSubject=63
MMAssertionMessageRedundantClassName=32
MMAssertionMessageRedundantLineNumber=11
MMAssertionMessageRedundantMethodName=49
MMAssertionMessageRestatesAssertion=15
MMAssertionMessageRestatesDerivedAssertion=16
MMAssertionMessageTooFewMeaningfulWords=59
MMAssertionMessageTooLong=17
MMAssertionMessageTooShort=71
MMAssertionMessageTrivialSupplier=37
MMAssertionMessageWhitespaceRun=36
MMCommentMessageDuplicate=56
MMCommentMessageMissing=82
MMCommentMessageMissingSubject=46
MMCommentMessageTooFewMeaningfulWords=35
MMCommentMessageTooShort=60
MMJavadocClassMessageDuplicate=24
MMJavadocClassMessageLongWord=23
MMJavadocClassMessageRedundantClassName=57
MMJavadocClassMessageTooFewMeaningfulWords=74
MMJavadocClassMessageTooShort=81
MMJavadocMemberMessageDuplicate=76
MMJavadocMemberMessageLongWord=21
MMJavadocMemberMessageRedundantMethodName=67
MMJavadocMemberMessageTooFewMeaningfulWords=77
MMJavadocMemberMessageTooShort=80
MMLacksPurpose=83
MMLogMessageContextless=8
MMLogMessageDuplicate=38
MMLogMessageGeneric=9
MMLogMessageIndexOnly=-1
MMLogMessageLongWord=-1
MMLogMessageMissing=50
MMLogMessageMissingSubject=28
MMLogMessageRedundantLineNumber=-1
MMLogMessageTooFewMeaningfulWords=12
MMLogMessageTooLong=-1
MMLogMessageTooShort=52
MMLogMessageTrivialSupplier=-1
MMLogMessageWhitespaceRun=10
MMLowEntropy=66
MMOverusedWord=72
MMPreconditionMessageContextless=-1
MMPreconditionMessageDuplicate=48
MMPreconditionMessageGeneric=13
MMPreconditionMessageIndexOnly=-1
MMPreconditionMessageLongWord=-1
MMPreconditionMessageRedundantLineNumber=-1
MMPreconditionMessageRestatesAssertion=-1
MMPreconditionMessageRestatesDerivedAssertion=-1
MMPreconditionMessageTooFewMeaningfulWords=44
MMPreconditionMessageTooLong=-1
MMPreconditionMessageTooShort=55
MMPreconditionMessageTrivialSupplier=18
MMPreconditionMessageWhitespaceRun=-1
MMThrowMessageContextless=54
MMThrowMessageDuplicate=73
MMThrowMessageGeneric=45
MMThrowMessageIndexOnly=19
MMThrowMessageLongWord=5
MMThrowMessageMissing=78
MMThrowMessageRedundantLineNumber=6
MMThrowMessageRestatesAssertion=20
MMThrowMessageRestatesDerivedAssertion=25
MMThrowMessageTooFewMeaningfulWords=65
MMThrowMessageTooLong=29
MMThrowMessageTooShort=62
MMThrowMessageWhitespaceRun=53
MMThrowNull=14
MMUnhandled=69
